---
- name: Verify required parameters
  assert:
    msg: "Required IEAM parameters were not provided"
    that:
      - ieam_cluster_url is defined
      - (ieam_cluster_url | trim | length) > 0
      - ieam_api_key is defined
      - (ieam_api_key | trim | length) > 0
      - ieam_organization is defined
      - (ieam_organization | trim | length) > 0

- name: Verify Node Name defined
  assert:
    msg: "`ieam_node_name` Must be Specified When Registering Edge Cluster"
    that:
      - ieam_node_name is defined
      - ieam_node_name | length > 0
  when: ieam_install_mode == "cluster"

- name: Set IEAM Facts
  set_fact:
    home_dir: "{{ ansible_env.HOME }}"
    ieam_css_url: "{{ ieam_cluster_url }}/edge-css/"

- name: Set Node Name Facts
  set_fact:
    ieam_node_name: "{{ ansible_hostname }}"
  when: ieam_node_name | trim | length == 0

- name: Create temp directory for IEAM Content
  file:
    path: "{{ ieam_tmp_dir }}"
    state: directory

- name: Download IEAM certificate
  get_url:
    url: "{{ ieam_css_url }}/api/v1/objects/IBM/agent_files/{{ ieam_certificate_name }}/data"
    dest: "{{ ieam_tmp_dir }}/{{ ieam_certificate_name }}"
    validate_certs: false
    force_basic_auth: yes
    url_username: "{{ ieam_organization }}/{{ ieam_username }}"
    url_password: "{{ ieam_api_key }}"
    mode: 0644

- name: Download software
  include_tasks: software.yml

- name: Run Device Installation
  include_tasks: device.yml
  when: ieam_install_mode == "device"

- name: Run Cluster Installation
  include_tasks: cluster.yml
  when: ieam_install_mode == "cluster"
