---
- name: Download Software
  become: yes
  get_url:
    url: "{{ ieam_cluster_url }}/api/cli/{{ item }}-linux-amd64"
    dest: "/usr/local/bin/{{ item }}"
    validate_certs: false
    mode: 0755
  loop:
    - cloudctl
    - kubectl
    - oc
  when: ieam_download_clis | bool

- name: Install Skopeo
  package:
    state: present
    name: skopeo
  when: ieam_install_mode == 'cluster' and ieam_cluster_install_skopeo | bool
