---

- name: Get Node List
  command: >
    hzn node list
  register: node_list_result
  changed_when: false

- name: Unregister Node
  block:
    - name: Unregister Node
      command:
        hzn unregister -f -r
      ignore_errors: true
      register: unregister_result

    - name: Unregister Node (Deep Clean)
      command:
        hzn unregister -f -r -D
      when: unregister_result.rc != 0
  when: (ieam_action == 'unregister') or (ieam_node_name != (node_list_result.stdout | from_json).id) or (ieam_pattern != (node_list_result.stdout | from_json).pattern)


